name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --workspace
    - name: Install latest nightly to test also against unstable feature flag
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            components: rustfmt
    - name: Run tests
      run: cargo test --all-features --verbose --workspace
    - name: Check Formatting
      run: cargo fmt --all -- --check
